# Generated by Django 5.2 on 2025-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#ffffff', help_text='Code couleur en hexadécimal (ex: #ffffff)', max_length=7)),
                ('logo_url', models.URLField(blank=True, help_text="URL de l'image du logo", null=True)),
            ],
        ),
    ]
