# Generated by Django 5.2 on 2025-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apparence',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='apparence',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='apparence',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Code couleur en hexadécimal pour le background (ex: #ffffff)', max_length=7),
        ),
        migrations.AddField(
            model_name='apparence',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo du site', null=True, upload_to='logos/'),
        ),
    ]
