# Generated by Django 5.2 on 2025-04-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_apparence_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparence',
            name='background_color',
            field=models.CharField(default='#ffffff', help_text='Code couleur en hexadécimal (ex: #ffffff)', max_length=7),
        ),
        migrations.AlterField(
            model_name='apparence',
            name='logo',
            field=models.URLField(blank=True, help_text="URL de l'image du logo", null=True),
        ),
    ]
