# Generated by Django 5.2 on 2025-04-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type_membre',
            field=models.CharField(default='simple', max_length=50),
        ),
    ]
